const foods = [
  {
    "name": "pizza margherita",
    "category": "Italian",
    "price": 15.99,
    "description": "Classic Italian pizza with fresh tomato sauce, mozzarella cheese, and basil",
    "calories": 250,
    "ingredients": ["tomato sauce", "mozzarella cheese", "basil", "olive oil", "pizza dough"],
    "preparationTime": 30,
    "difficulty": "Medium",
    "isVegetarian": true,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.5,
    "chef": "Mario Rossi",
    "restaurant": "Bella Italia"
  },
  {
    "name": "sushi salmon roll",
    "category": "Japanese", 
    "price": 25.00,
    "description": "Fresh salmon sushi roll with avocado and cucumber",
    "calories": 200,
    "ingredients": ["salmon", "avocado", "cucumber", "sushi rice", "nori", "wasabi"],
    "preparationTime": 45,
    "difficulty": "Hard",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.8,
    "chef": "Takeshi Yamamoto",
    "restaurant": "Sakura Sushi"
  },
  {
    "name": "classic burger",
    "category": "American",
    "price": 12.99,
    "description": "Juicy beef burger with lettuce, tomato, and fries",
    "calories": 650,
    "ingredients": ["beef patty", "lettuce", "tomato", "onion", "pickle", "burger bun"],
    "preparationTime": 15,
    "difficulty": "Easy",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.2,
    "chef": "John Smith",
    "restaurant": "Burger House"
  },
  {
    "name": "pad thai",
    "category": "Thai",
    "price": 13.50,
    "description": "Traditional Thai stir-fried rice noodles with shrimp and peanuts",
    "calories": 380,
    "ingredients": ["rice noodles", "shrimp", "bean sprouts", "peanuts", "lime", "fish sauce"],
    "preparationTime": 20,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.6,
    "chef": "Siriporn Thanakit",
    "restaurant": "Bangkok Street"
  },
  {
    "name": "chicken tikka masala",
    "category": "Indian",
    "price": 16.75,
    "description": "Tender chicken in creamy tomato-based curry sauce",
    "calories": 420,
    "ingredients": ["chicken breast", "tomato sauce", "cream", "onion", "garlic", "garam masala"],
    "preparationTime": 35,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.7,
    "chef": "Raj Patel",
    "restaurant": "Spice Garden"
  },
  {
    "name": "beef tacos",
    "category": "Mexican",
    "price": 11.25,
    "description": "Three soft tacos with seasoned ground beef and fresh toppings",
    "calories": 480,
    "ingredients": ["ground beef", "corn tortillas", "lettuce", "cheese", "salsa", "sour cream"],
    "preparationTime": 25,
    "difficulty": "Easy",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.3,
    "chef": "Carlos Rodriguez",
    "restaurant": "El Sombrero"
  },
  {
    "name": "ramen tonkotsu", 
    "category": "Japanese",
    "price": 14.00,
    "description": "Rich pork bone broth ramen with chashu pork and soft-boiled egg",
    "calories": 550,
    "ingredients": ["pork broth", "ramen noodles", "chashu pork", "soft-boiled egg", "green onion", "nori"],
    "preparationTime": 20,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.9,
    "chef": "Hiroshi Tanaka",
    "restaurant": "Ramen Ichiban"
  },
  {
    "name": "pasta carbonara",
    "category": "Italian",
    "price": 18.50,
    "description": "Creamy pasta with eggs, cheese, pancetta, and black pepper",
    "calories": 520,
    "ingredients": ["spaghetti", "eggs", "parmesan cheese", "pancetta", "black pepper", "olive oil"],
    "preparationTime": 25,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.6,
    "chef": "Giuseppe Bianchi",
    "restaurant": "Nonna's Kitchen"
  },
  {
    "name": "kung pao chicken",
    "category": "Chinese",
    "price": 15.80,
    "description": "Spicy Sichuan dish with chicken, peanuts, and dried chilies",
    "calories": 400,
    "ingredients": ["chicken thighs", "peanuts", "dried chilies", "soy sauce", "rice wine", "garlic"],
    "preparationTime": 30,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.4,
    "chef": "Wei Chen",
    "restaurant": "Golden Dragon"
  },
  {
    "name": "coq au vin",
    "category": "French",
    "price": 28.00,
    "description": "Classic French braised chicken in red wine with mushrooms",
    "calories": 380,
    "ingredients": ["chicken", "red wine", "mushrooms", "bacon", "onions", "herbs"],
    "preparationTime": 90,
    "difficulty": "Hard",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.8,
    "chef": "Pierre Dubois", 
    "restaurant": "Le Petit Bistro"
  },
  {
    "name": "pho bo",
    "category": "Vietnamese",
    "price": 12.50,
    "description": "Traditional Vietnamese beef noodle soup with herbs",
    "calories": 350,
    "ingredients": ["rice noodles", "beef broth", "beef slices", "onion", "cilantro", "lime"],
    "preparationTime": 15,
    "difficulty": "Easy",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.7,
    "chef": "Nguyen Van",
    "restaurant": "Saigon Street"
  },
  {
    "name": "bibimbap",
    "category": "Korean",
    "price": 16.25,
    "description": "Korean mixed rice bowl with vegetables, meat, and fried egg",
    "calories": 480,
    "ingredients": ["rice", "beef", "spinach", "carrots", "mushrooms", "fried egg", "gochujang"],
    "preparationTime": 40,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.5,
    "chef": "Kim Min-jun",
    "restaurant": "Seoul Kitchen"
  },
  {
    "name": "fish and chips",
    "category": "American",
    "price": 17.99,
    "description": "Beer-battered fish with crispy fries and mushy peas",
    "calories": 720,
    "ingredients": ["cod fish", "beer batter", "potatoes", "mushy peas", "tartar sauce", "malt vinegar"],
    "preparationTime": 25,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.1,
    "chef": "Tommy Wilson",
    "restaurant": "Coastal Catch"
  },
  {
    "name": "vegetable curry",
    "category": "Indian",
    "price": 14.25,
    "description": "Mixed vegetables in aromatic coconut curry sauce",
    "calories": 320,
    "ingredients": ["mixed vegetables", "coconut milk", "curry powder", "onion", "garlic", "ginger"],
    "preparationTime": 30,
    "difficulty": "Easy",
    "isVegetarian": true,
    "isVegan": true,
    "isGlutenFree": true,
    "rating": 4.3,
    "chef": "Priya Sharma",
    "restaurant": "Vegetarian Delight"
  },
  {
    "name": "quesadilla",
    "category": "Mexican",
    "price": 9.75,
    "description": "Grilled tortilla filled with cheese and chicken",
    "calories": 420,
    "ingredients": ["flour tortillas", "cheese", "chicken", "bell peppers", "onions", "jalapeños"],
    "preparationTime": 15,
    "difficulty": "Easy",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.2,
    "chef": "Maria Gonzalez",
    "restaurant": "Fiesta Mexicana"
  },
  {
    "name": "tom yum soup",
    "category": "Thai",
    "price": 11.00,
    "description": "Spicy and sour Thai soup with shrimp and mushrooms",
    "calories": 180,
    "ingredients": ["shrimp", "mushrooms", "lemongrass", "lime leaves", "chili", "lime juice"],
    "preparationTime": 20,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.6,
    "chef": "Somchai Prasert",
    "restaurant": "Thai Spice"
  },
  {
    "name": "duck confit",
    "category": "French",
    "price": 32.00,
    "description": "Slow-cooked duck leg with crispy skin and garlic potatoes",
    "calories": 450,
    "ingredients": ["duck leg", "duck fat", "garlic", "potatoes", "thyme", "rosemary"],
    "preparationTime": 180,
    "difficulty": "Hard",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.9,
    "chef": "Antoine Leclerc",
    "restaurant": "Le Gourmet"
  },
  {
    "name": "sweet and sour pork",
    "category": "Chinese", 
    "price": 16.50,
    "description": "Crispy pork pieces in tangy sweet and sour sauce",
    "calories": 480,
    "ingredients": ["pork shoulder", "pineapple", "bell peppers", "vinegar", "sugar", "ketchup"],
    "preparationTime": 35,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.0,
    "chef": "Liu Xiaoming",
    "restaurant": "China Garden"
  },
  {
    "name": "banh mi",
    "category": "Vietnamese",
    "price": 8.50,
    "description": "Vietnamese baguette sandwich with grilled pork and pickled vegetables",
    "calories": 380,
    "ingredients": ["baguette", "grilled pork", "pickled vegetables", "cilantro", "jalapeños", "pâté"],
    "preparationTime": 10,
    "difficulty": "Easy",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": false,
    "rating": 4.4,
    "chef": "Tran Minh",
    "restaurant": "Vietnam Deli"
  },
  {
    "name": "kimchi jjigae",
    "category": "Korean",
    "price": 13.75,
    "description": "Spicy Korean kimchi stew with pork and tofu",
    "calories": 300,
    "ingredients": ["kimchi", "pork belly", "tofu", "onion", "garlic", "gochugaru"],
    "preparationTime": 25,
    "difficulty": "Medium",
    "isVegetarian": false,
    "isVegan": false,
    "isGlutenFree": true,
    "rating": 4.7,
    "chef": "Park Ji-hoon",
    "restaurant": "Korean BBQ House"
  }
];

module.exports = foods;